INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'carweb', 'carweb', 2, 'password');

INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '1', 'Kombi', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '2', 'Kombi', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '3', 'Sedan', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '4', 'Stasjonsvogn', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '5', 'Flerbruksbil', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '6', 'Coupe', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '7', 'Cabriolet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '8', 'Pick-up', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '9', 'Off-road', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'karosserifasong', '10', 'Kasse', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'kjoretoygruppe', '1', 'Personbil', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'kjoretoygruppe', '2', 'Varebil', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'kjoretoygruppe', '3', 'Kombinertbil', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'kjoretoygruppe', '4', 'Minibuss', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'kjoretoygruppe', '5', 'Lett lastebil', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'B', 'Bensin', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'D', 'Diesel', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'G', 'Gass', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'Hybrid', 'Hybrid', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', '5', 'Hybrid', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'S', 'Elektrisk', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'El', 'Elektrisk', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', '6', 'Elektrisk', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', 'Metanol', 'Metanol', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('carweb', 'drivstoff', '4', 'Metanol', 1311147487320);