INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'finnjob', 'rcconsas', 2, 'password');
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'rcconsas', 1747664, 'RC Consultants', 'password' FROM partnerlogin WHERE login='rcconsas';

INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/officesecr',102,'Kontormedarbeider/Sekretær', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/switchbreception',103,'Sentralbord/Resepsjon', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/studyadm',102,'Kontormedarbeider/Sekretær', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/custsupporderhandl',104,'Kundeservice/Ordremottak', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/managment',105,'Administrativ ledelse', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/archivedocument',106,'Dokumentbehandling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/emprelrecruiting',107,'Personalhåndtering/Rekruttering', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/training',2804,'Voksenopplæring/Kurs', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/executiveofficer',108,'Saksbehandler', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'admoffice/other',100,'Administrasjon, økonomi og juss', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/bankfinserv',201,'Bank/Finansielle tjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/insurpenfund',202,'Forsikring/Fond', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/medanalysis',203,'Megling/Analyse', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/bankadminexec',201,'Bank/Finansielle tjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/realestatenego',204,'Eiendomsmegling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/bankadvicer',205,'Rådgiver', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/bankexecoff',201,'Bank/Finansielle tjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'bankfinanceinsurance/other',201,'Bank/Finansielle tjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'researchdevelop/rdscieng',2901,'Naturvitenskap og teknikk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'researchdevelop/rdsocscihum',2902,'Samf. vitenskap og humanistiske fag', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'researchdevelop/other',2900,'Forskning og utvikling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/docdentvet',501,'Lege', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/nursing',510,'Sykepleier', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/psychpsycserv',800,'Omsorg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/physergoserv',512,'Fysioterapi/Ergoterapi', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/socialserv',800,'Omsorg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/pharmacy',701,'Apotekertjenester/Farmasi', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/chiropractor',513,'Kiropraktor', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/veterenarian',515,'Veterinær', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/radiography',800,'Omsorg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'healthwelfare/other',490,'Helse, medisin og omsorg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/hotel',2501,'Hotellvirksomhet/ overnatting', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/otherovernight',2501,'Hotellvirksomhet/ overnatting', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/restbar',2600,'Restaurant og kjøkken', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/booking',2502,'Booking', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/cantcathousekeep',2600,'Restaurant og kjøkken', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/travel',2500,'Hotell og Reiseliv', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'hotelrestauranttrav/other',2500,'Hotell og Reiseliv', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/skilledtrad',2200,'Håndverksfag/bygg og anlegg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/techconstruction',2202,'Tekniske byggfag', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/mechoccup',2203,'Mekaniske yrker', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/buildconstruction',2204,'Bygg og anlegg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/carmechanic',2205,'Bilmekaniker', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/unskilledtrad',2206,'Ufaglært håndverk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/servmechanic',2207,'Servicemekaniker', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'buildconstr/other',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/electroptical',2301,'Elektriske produkter', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/energywatsupply',2302,'Energi og vannforsyning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/pharmind',701,'Apotekertjenester/Farmasi', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/graphicalind',2303,'Grafisk industri', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/rubplasticsmin',2304,'Gummi- plast- og mineralvarer', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/chempetind',2305,'Kjemisk industri/ Petroleumsindustri', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/metals',2306,'Metallurgisk industri/Metallvarer', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/foodbevtob',2307,'Nærings- og nytelsesmidler', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/textclothinf',2308,'Tekstindustri og bekledning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/transpmachequip',2309,'Transportmidler/Maskiner og utstyr', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/woodfurnind',2310,'Treindustri', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/worksind',2311,'Verksindustri', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'industrymanuf/other',2300,'Industri og produksjon', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/buidconstruction',2204,'Bygg og anlegg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/computereng',2690,'Data og IKT', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/chembio',2901,'Naturvitenskap og teknikk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/physmat',2901,'Naturvitenskap og teknikk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/energy',2302,'Energi og vannforsyning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/geopettech',2402,'Geologi/Geofysikk/Reservoar', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/marintech',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/materialtech',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/cybernetics',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/engmech',2309,'Transportmidler/Maskiner og utstyr', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/engelectronics',2301,'Elektriske produkter', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/engvvs',2200,'Håndverksfag/bygg og anlegg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/engprojmanag',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/engcontract',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'engineering/other',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'profindbodies/employerorg',2101,'Næringslivs- og arbeidsgiverorg.', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'profindbodies/employeeorg',2102,'Arbeidstagerorganisasjoner', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'profindbodies/charityorg',2103,'Ideelle organisasjoner', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'profindbodies/internatorg',2104,'Internasjonale organisasjoner', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'profindbodies/other',1890,'Kultur, idrett og organisasjoner', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/applicdev',2701,'Applikasjonsutvikling/ programmering', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/businessdev',2702,'Forretningsutvikling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/support',2703,'Support', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/plantmachdev',2704,'Utvikling av infrastruktur og maskinvare', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/plantappoper',2705,'Drift av applikasjoner og infrastruktur', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/salesmarketing',1300,'Salg og markedsføring', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'ittelecominternet/other',2690,'Data og IKT', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/farmgardcentre',3201,'Dyrking', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/domfarming',3303,'Husdyrhold', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/forestry',3203,'Skogbruk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/huntestmng',3300,'Jakt/Viltstell', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/fishhunt',3301,'Fiske og fangst', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/fishfarm',3302,'Oppdrettsnæring', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'farmforestryhuntfish/other',3090,'Primærnæringer', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/architect',2200,'Håndverksfag/bygg og anlegg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/techconsult',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/legalserv',400,'Jus', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/propmanagment',204,'Eiendomsmegling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/busdevstrat',2702,'Forretningsutvikling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/orgdevelopment',107,'Personalhåndtering/Rekruttering', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/recruitment',107,'Personalhåndtering/Rekruttering', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/revtaxadv',307,'Revisjon/Skatterådgivning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'consulting/other',11,'Annet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'artsculture/theaoperaballett',1901,'Teater/Opera/Ballett', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'artsculture/musicdance',1902,'Musikk/Dans', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'artsculture/artactiv',1900,'Kunst og kultur', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'artsculture/librmuseums',1903,'Bibliotek/Museer/Galleri', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'artsculture/sport',2000,'Idrett', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'artsculture/other',1900,'Kunst og kultur', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'aviationaerospace/flightcontroff',1606,'Flygeleder', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'aviationaerospace/pilot',1607,'Flyger', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'aviationaerospace/planemechanic',1608,'Flymekaniker/Teknisk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'aviationaerospace/cabincrew',1609,'Kabinpersonell', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'aviationaerospace/groundcrew',1610,'Bakkepersonell', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'aviationaerospace/other',1605,'Luftfart', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/advertinfo',1201,'Reklame', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/commadvice',1200,'Media, informasjon og PR', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/internett',1205,'Internett', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/journalism',1202,'Journalistikk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/radiotvfilmvideo',1203,'Radio/TV/Film/Video', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/printing',1204,'Trykte Media', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/publishing',1206,'Forlagvirksomhet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'mediainfopr/other',1200,'Media, informasjon og PR', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/policefirecust',1000,'Sikkerhet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/healthsocserv',490,'Helse, medisin og omsorg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/churcheduresearch',2790,'Utdanning og Forskning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/offconsultant',100,'Administrasjon, økonomi og juss', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/defforpol',1004,'Forsvar', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/taxnatinsur',100,'Administrasjon, økonomi og juss', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/legprisserv',1000,'Sikkerhet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/offcaseworker',108,'Saksbehandler', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/publicmng',100,'Administrasjon, økonomi og juss', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/techserv',100,'Administrasjon, økonomi og juss', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/foreignaff',100,'Administrasjon, økonomi og juss', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'publicserv/other',11,'Annet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/oilgas',2401,'Olje- og gassutvinning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/geology',2402,'Geologi/Geofysikk/Reservoar', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/oilgassupport',2403,'Tjenester tilknyttet olje- og gassutvinning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/drilling',2404,'Drilling/Logging/Brønn/Boring', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/extractionmining',2405,'Utvinning av råstoffer/Bergverksdrift', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/offengineering',2190,'Industri, bygg, offshore', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/offoperator',2406,'Operatør/Vedlikehold', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/offhms',2407,'Helse/Miljø/Sikkerhet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/offprojmanagment',2408,'Prosjektledelse', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/offresearch',2409,'Forskning og Teknologi Utvikling', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/offmanagment',2410,'Ledelse og Fellestjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/technautical',2411,'Nautisk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/techmar',2412,'Teknisk - maritim', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'offshoreexploit/other',2400,'On-/ offshore, olje og gass', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/persfysioergo',512,'Fysioterapi/Ergoterapi', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/hairbeauty',601,'Hår- og skjønnhetspleie', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/perschiropractor',513,'Kiropraktor', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/domhelpgard',11,'Annet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/fitnesscentre',11,'Annet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/caretakserv',905,'Vaktmestertjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/securityserv',1101,'Vekter', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/laundrydryclean',901,'Rengjøringsmedarbeider', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'personalserv/other',11,'Annet', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'cleanwaste/cleaningpersonell',901,'Rengjøringsmedarbeider', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'cleanwaste/watersewserv',900,'Renhold, vedlikehold og renovasjon', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'cleanwaste/wastemng',903,'Renovasjon', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'cleanwaste/vermincontroll',904,'Skadesanering', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'cleanwaste/other',900,'Renhold, vedlikehold og renovasjon', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'salesmarketing/servicessales',1303,'Tjenestesalg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'salesmarketing/telemarketing',1304,'Telemarketing', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'salesmarketing/productsales',1305,'Produktsalg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'salesmarketing/marketing',1300,'Salg og markedsføring', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'salesmarketing/other',1300,'Salg og markedsføring', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'salesmarketing/customerservice',104,'Kundeservice og ordremottak', 1311147487320);

INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/haulage',1600,'Landtransport', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/shipping',1602,'Sjøfart', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/tranbuyer',1704,'Innkjøpsansvarlig', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/airtransport',1605,'Luftfart', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/trasnportserv',1611,'Transportknyttede tjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/postdelivery',1801,'Post- og budtjenester', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/logisticwarehouse',1700,'Lager', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'transpologisticswareh/other',1590,'Transport, lager og logistikk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/kindergarden',805,'Barnehage', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/school',2801,'Grunnskole', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/professorship',2805,'Professorat/Stipendiat', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/highschool',2802,'Videregående skole', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/univcollege',2803,'Universitet/Høgskole', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/adultedu',2804,'Voksenopplæring/Kurs', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'eduteach/other',2790,'Utdanning og Forskning', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'retail/agencywholesale',1501,'Agentur- engroshandel', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'retail/decorator',1502,'Dekoratør', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'retail/retailtrade',1503,'Detaljhandel/Butikksalg', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'retail/franchise',1504,'Franchisetager', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'retail/maintrep',1505,'Reparasjon og vedlikehold', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'retail/other',1500,'Varehandel', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/accountcontrol',300,'Økonomi og regnskap', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/economyfinance',302,'Økonomi/Finans', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/puchlogistics',303,'Innkjøp/Logistikk', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/payoffice',304,'Lønn', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/other',300,'Økonomi og regnskap', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/revision',305,'Revisjon', 1311147487320);
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('finnjob', 'categories', 'economycontrolling/other',300,'Økonomi og regnskap', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'sectors', 'private', 'Privat', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'sectors', 'public', 'Offentlig', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'sectors', 'organisations', 'Organisasjoner', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'duration', 'permanent', 'Fast', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'duration', 'fixedcontract', 'Engasjement', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'duration', 'temporary', 'Vikariat', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'duration', 'seasonal', 'Sommer/Sesong', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'senmanager', 'Toppleder', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'midmanager', 'Mellomleder', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'projmanager', 'Prosjektleder', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'advisor', 'Rådgiver', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'profexp', 'Fagperson', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'salespers', 'Selger', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'custreloff', 'Kundebehandler', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'operator', 'Operatør', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'role', 'other', 'Andre', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'extent', 'fulltime', 'Heltid', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'extent', 'parttime', 'Deltid', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'modus', 'yes', 'Ja', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'modus', 'no', 'Nei', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'heading', 'OFFER', 'Tilbud', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'heading', 'TASKS', 'Oppgaver', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'heading', 'QUALIFICATIONS', 'Kvalifikasjoner', 1311147487320);
INSERT INTO valuemap (format, field, lookup, zettvalue, updatedtime) VALUES ('finnjob', 'heading', 'PERSONAL_QUALITIES', 'Personlige egenskaper', 1311147487320);