INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'til salgs', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'nybygg', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'bolig_salg', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'fritid_salg', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'næring_salg', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'bolig_tomt', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'næring_tomt', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'til leie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'bolig_leie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'fritid_utleie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'næring_utleie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'ønskes leid', 'WANTED_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'transaction', 'bolig_ønskes_leid', 'WANTED_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'country', 'NO', 'Norge', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'country', 'DK', 'Danmark', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'country', 'SE', 'Sverige', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'selveier', 'Selveier', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'borettslag', 'Borettslag', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'andel', 'Borettslag', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'obligasjonsleilighet', 'Obligasjonsleilighet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'obligasjon', 'Obligasjonsleilighet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'aksjeleilighet', 'Aksjeleilighet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'aksje', 'Aksjeleilighet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'timeshare andel', 'Timeshare andel', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('itmakeriet', 'ownership', 'annet', 'Annet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'hybel', 'Hybel',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'leilighet', 'Leilighet',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'enebolig', 'Enebolig',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'rekkehus', 'Rekkehus',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'tomannsbolig', 'Tomannsbolig',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'småbruk', 'Småbruk',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'smaabruk', 'Småbruk',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'bofellesskap', 'Bofellesskap',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'boligtomt', 'Boligtomt',16550, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'bolig_tomt', 'Boligtomt',16550, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'tomt', 'Boligtomt',16550, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'garasje/parkering', 'Garasje/Parkering',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'annet', 'Annet',16100, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'hyttetomt', 'Hyttetomt',16650, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'hytte_tomt', 'Hyttetomt',16650, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'fritidsbolig', 'Fritidsbolig',16300, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'annet-fritid', 'Fritidsbolig',16300, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'ferieleilighet', 'Ferieleilighet',16300, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'hytte', 'Hytte',16300, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'kontor', 'Kontor',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'forretningslokale/butikk', 'Forretningslokale/Butikk',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'forretning', 'Forretningslokale/Butikk',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'produksjon/industri', 'Produksjon/Industri',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'lager', 'Lager',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'kombinasjonslokaler', 'Kombinasjonslokaler',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'kombinasjonslokale', 'Kombinasjonslokaler',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'gårdsbruk', 'Gårdsbruk',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'gaardsbruk', 'Gårdsbruk',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'flermannsbolig/bygårder', 'Flermannsbolig/Bygårder',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'flermannsbolig', 'Flermannsbolig/Bygårder',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'kjøpesenter', 'Kjøpesenter',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'verksted', 'Verksted',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'hotell/overnatting', 'Hotell/Overnatting',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'hotell', 'Hotell/Overnatting',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'serveringslokale/kantine', 'Serveringslokale/Kantine',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'undervisning/arrangement', 'Undervisning/Arrangement',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'prosjekt', 'Prosjekt',16200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'kuriositeter', 'Kuriositeter',16400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('itmakeriet', 'type', 'næringstomt', 'Næringstomt',16600, 1311147487320);

INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekobbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp1301756', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp1308152', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp503781', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp21863', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp1228855', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp1228860', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeeie', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrvls', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrvlskog', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehglnd', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemoom', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenosar', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegeg', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehneas', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrvfred', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrval', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekvas', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenotarstvg', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeeiembl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenonor', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeeiev', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrvb', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'ftp756825', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemaja', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemoru', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeadir', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyaa', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyhe', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenykr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyna', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyst', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenymo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyne', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenymt', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyle', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenyro', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zevest', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrdr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegaro', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekbbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegamo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zembbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerbbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemebe', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehabo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zedobbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemebv', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zelysw', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeabbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehone', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zering', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerita', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehaub', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegaha', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zedrme', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zebrend', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrtr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemobo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerena', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegala', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemors', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zemorf', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegabb', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zegaho', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zednbn', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zenypr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrto', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrra', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekraa', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zepbbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrsk', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrpo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrba', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zesbol', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zereie', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehena', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zehemo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeheel', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeheha', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeheko', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeheri', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeebbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zeitma', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerhal', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerham', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerhol', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zebbme', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerive', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zerito', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zearli', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zearfo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'itmakeriet', 'zekrha', 2, 'password');