INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Ingen kontaktinfo skal vises', 'SHOW_NONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Email vises', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Telefonnummer vises', 'SHOW_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Navn og telefonnummer vises', 'SHOW_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Navn og Telefonnummer', 'SHOW_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Epost og telefonnummer vises', 'SHOW_EMAIL_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'Email, navn og telefonnummer vises', 'SHOW_EMAIL_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'privacy', 'All kontaktinfo kan vises på annonsen.', 'SHOW_ALL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'defaultprivacy', '10009', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'defaultprivacy', '10016', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'overrideprivacy', '10016', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'defaultprivacy', '10061', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'overrideprivacy', '10061', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'defaultprivacy', '10063', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'overrideprivacy', '10063', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'defaultprivacy', '10020', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'overrideprivacy', '10020', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Til salgs', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Selges', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Til leie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Ønskes kjøpt', 'WANTED_BUY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Ønskes leid', 'WANTED_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Byttes', 'TRADE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Gis bort', 'GIVE_AWAY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Gis bort/Byttes', 'GIVE_AWAY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Arbeidskraft søkes', 'SERVICES_WANTED', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Tapt/Funnet', 'LOST_AND_FOUND', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Annet', 'OTHER', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Stilling ledig', 'JOB_AVAILABLE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'country', 'Norway', 'Norge', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'source', 'Bilforhandler', 'Forhandler', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'source', 'Privat selger', 'Privat', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'workarea', 'Dagmamma/Barnepass', 'Dagmamma/Praktikant', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'workarea', 'Håndtverkstjenster', 'Håndverksfag', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', 'Snøscootere', 'Snøscooter', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', 'Mat og Drikke', 'Mat og drikke', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', 'Garasje/Opplag', 'Garasje/opplag', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', 'Sport og Fritid', 'Sport- og fritidsutstyr', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', 'Skjærgårdsjeep/landstedsbåt', 'Skjærgårdsjeep/Landstedbåt', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', '--- Stort og smått ---', 'Annet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'type', 'Diverse', 'Annet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('mactive', 'transaction', 'Arbeid utføres', 'JOB_PERFORMED', 1311147487320);

INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'mactive', 'zbhall', 2, 'password');