INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'A', 'Østerrike', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'B', 'Belgia', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'HR', 'Kroatia', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'CZ', 'Tsjekkia', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'DK', 'Danmark', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'F', 'Frankrike', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'D', 'Tyskland', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'G', 'Hellas', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'H', 'Ungarn', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'IE', 'Irland', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'I', 'Italia', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'NL', 'Nederland', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'N', 'Norge', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'PL', 'Polen', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'PT', 'Portugal', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'SL', 'Slovakia', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'E', 'Spania', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'S', 'Sverige', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'country', 'UK', 'Storbritania', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'stars', '1', '1 stjerne', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'stars', '2', '2 stjerner', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'stars', '3', '3 stjerner', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'stars', '4', '4 stjerner', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'stars', '5', '5 stjerner', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '1', 'Overlevering mandager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '2', 'Overlevering tirsdager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '3', 'Overlevering onsdager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '4', 'Overlevering torsdager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '5', 'Overlevering fredager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '6', 'Overlevering lørdager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'dayofchange', '7', 'Overlevering søndager fra kl. 16.00', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'optionalarrival', 'A', 'Valgfri ankomstdag i enkelte perioder', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'optionalarrival', 'B', 'Valgfri ankomstdag i enkelte perioder', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'pets', 'Y', 'Husdyr tillatt', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'waterpark', 'Y', 'Badeland', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'tennis', 'Y', 'Tennisbane i nærheten', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'golf', 'Y', 'Golfbane i nærheten', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('novasol', 'art', 'Y', 'Kunstby', 1311147487320);

INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'novasol', 'novasol', 2, 'password');
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'novasol', 21947, 'novasol', 'password' FROM partnerlogin WHERE login='novasol';