INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'Ingen kontaktinfo skal vises', 'SHOW_NONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'Email vises', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'Telefonnummer vises', 'SHOW_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'Navn og telefonnummer vises', 'SHOW_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'Epost og telefonnummer vises', 'SHOW_EMAIL_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'Email, navn og telefonnummer vises', 'SHOW_EMAIL_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'privacy', 'All kontaktinfo kan vises på annonsen', 'SHOW_ALL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Til salgs', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Til leie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Ønskes kjøpt', 'WANTED_BUY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Ønskes leid', 'WANTED_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Byttes', 'TRADE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Gis bort', 'GIVE_AWAY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Gis bort/Byttes', 'GIVE_AWAY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Arbeidskraft søkes', 'SERVICES_WANTED', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Tapt/Funnet', 'LOST_AND_FOUND', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Annet', 'OTHER', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Stilling ledig', 'JOB_AVAILABLE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'country', 'Norway', 'Norge', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'taxpaid', '0', 'Nei', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'taxpaid', '1', 'Ja', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Håndtverkstjenester', 'Håndverksfag', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Salgstjenester', 'Salg', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Helse, Sosial og Omsorg', 'Helse, Sykepleie, Sosial og Omsorg', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Helse, sykepleie, sosial og omsorg', 'Helse, Sykepleie, Sosial og Omsorg', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Bud- og transport tjenester', 'Bud- og Transport-tjenester', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Tomterydding/Hagearbeid/Jordbruk', 'Jordbruk, Skogbruk og Fiske', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'IT-tjenester', 'Data og IT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Finansielle/økonomiske tjenester', 'Bank og Finans', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'workarea', 'Helse og skjønnhet', 'Helse og Skjønnhet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Mat og Drikke', 'Mat og drikke', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Landbruks- maskiner/utstyr', 'Landbruk - maskiner/utstyr', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Snøscootere', 'Snøscooter', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Sport og Fritid', 'Sport- og fritidsutstyr', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Gummibåt/jolle/robåt', 'Gummibåt/Jolle/Robåt', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Skjærgårdsjeep/landstedsbåt', 'Skjærgårdsjeep/Landstedbåt', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Yrkesbåt/sjark/skøyte', 'Yrkesbåt/Sjark/Skøyte', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Trebåt/snekke', 'Trebåt/Snekke', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Hus og Hjem diverse', 'Annet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Bolig', 'Hus og Hjem diverse', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'type', 'Andre', 'Annet', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('onlinebooking', 'transaction', 'Arbeid utføres', 'JOB_PERFORMED', 1311147487320);

INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'onlinebooking', 'zoravn', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ('onlinebooking', 'zobooking', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'onlinebooking', 'zojobs', 2, 'password');