INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'rettbemanning', 'rettbemanning', 2, 'password');
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'rettbemanning', 40357, 'Rettbemanning', 'password' FROM partnerlogin WHERE login='rettbemanning';

INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','AdministrativLedelse',11,'Annet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Administrativledelse/HR',2690,'Data og IKT', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Aministrasjon/Kontor/Personal',105,'Administrativ ledelse', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Anleggsgartner',101,'Administrasjon, personal og kontor', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Anleggsleder',106,'Dokumentbehandling', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Annet',303,'Innkjøp/Logistikk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Annetfaglærthåndverk',102,'Kontormedarbeider/Sekretær', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Annonse/Reklame',104,'Kundeservice/Ordremottak', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Arbeidstakerorganisasjoner',306,'Utdanning og forskning / Utdanning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Arkitetvirksomhet',107,'Personalhåndtering/Rekruttering', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Arkiv/Dokumentbehandler',306,'Administrasjon, økonomi og juss', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Automasjon/Instrumentering',306,'Administrasjon, økonomi og juss', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Bank/Finansielletjenester',103,'Sentralbord/Resepsjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Bank/Finans/Forsikring',201,'Bank/Finansielle tjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Bar/Restaurant',204,'Eiendomsmegling', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Barnehage',205,'Rådgiver', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Bibliotek/Museer/Galleri',202,'Forsikring/Fond', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Blikkenslager',701,'Apotekertjenester/Farmasi', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Booking',512,'Fysioterapi/Ergoterapi', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Booking/Respsjonist',508,'Helsesøster', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Brønn/Boring/Drilling/Logging',509,'Hjelpepleie', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Butikk/Detaljehandel',509,'Hjelpepleie', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Byggoganleggsmedarbeider',501,'Lege', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Bygg-oganleggsingeniør',701,'Apotekertjenester/Farmasi', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Byggeleder',503,'Legesekretær/Legeassistent', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Catering/Kantine/Storhusholdning',800,'Omsorg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Controller',510,'Sykepleier', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Dataingeniør',504,'Tannhelse', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Dekoratør',504,'Tannhelse', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Eiendomsmegler',2490,'Resturant og reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Elektriker',2502,'Booking', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Elektriskeogoptiskeprodukter',2502,'Booking', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Elektroingeniør',2300,'Kantine/Storhusholdning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Energi-ogvannforsyning',2501,'Hotellvirksomhet/ overnatting', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Energi/Kraftingeniør',2501,'Hotellvirksomhet/ overnatting', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Engineering',2604,'Restaurant', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Farmasøyt',2501,'Hotellvirksomhet/ overnatting', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Farmasøytiskindustri',2601,'restaurant og reiseliv / restaurant_og_kjøkken / kantine_og_storhusholdning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Fengselsbetjent',2602,'Kokk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Finansrådgiver',2602,'Kokk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Forlagsvirksomhet',2602,'Kokk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Forsikring/Fond/Pensjonsfond',2500,'restaurant_og_reiseliv__hotell_og_reiseliv.', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Forskalingssnekker',2500,'Hotell og Reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Forskning',2500,'Hotell og Reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Førskole/SFO',2500,'Hotell og Reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Franchisetaker',2500,'Hotell og Reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Fysioterapeut',2605,'Servitør', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Fystikkogmatematikk',2500,'Hotell og Reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Geofag/Petroleumsteknologi',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Geologi/Geofysikk/Reservoar',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Grafiskindustri',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Grunnskole',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Gummi,plastogmineralvare',2204,'Bygg og anlegg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Håndverk/Byggoganlegg',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hår-/Skjønnhetspleie',2208,'Elektriker', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Helse/Miljø/Sikkerhet',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Helse/Sosial',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Helsestasjon',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hjelpepleier',2200,'Bygg og anlegg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hjemmetjeneste',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','HMS',2200,'Bygg og anlegg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hotell/Restaurant/Storhusholdning',2205,'Bilmekaniker', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hotellmedarbeider/Værelse',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hotellsjef',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Hovmester',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Husøkonom',2206,'Ufaglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','IK-Mat',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Indrettshøyskole',2201,'Faglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Industri/produksjon',2206,'Ufaglært håndverk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Ingeniør',2301,'Elektriske produkter', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Innkjøp(ingeniør)',2302,'Energi og vannforsyning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Innkjøp(Transport)',2300,'bygg_og_offshore__industri_og_produksjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Innkjøp/Kontrakt',2300,'bygg_og_offshore__industri_og_produksjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Interesseorganisasjon',2304,'Gummi- plast- og mineralvarer', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Internasjonaleorganisasjoner',2305,'Kjemisk industri/ Petroleumsindustri', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Internett',2311,'bygg_og_offshore__industri_og_produksjon__verksindustri', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Isolatør',2306,'Metallurgisk industri/Metallvarer', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','IT/Telekommuniasjon/Internett',2307,'Nærings- og nytelsesmidler', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','IT/Telekommunikasjon/Internett',2311,'bygg_og_offshore__industri_og_produksjon__verksindustri', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Jernbindere',2309,'Transportmidler/Maskiner og utstyr', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Jounalistikk',2310,'Treindustri', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Juridisketjenester',2190,'industri%2C_bygg_og_offshore', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kjemi/Biologi',2200,'Håndverksfag/bygg og anlegg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kjemiskindustri/petroleumsindustri',2690,'Data og IKT', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kjøle/kuldetekniker',2302,'Energi og vannforsyning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kokkm/fagbrev',2790,'utdanning_og_forskning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kokku/fagbrev',2402,'Geologi/Geofysikk/Reservoar', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kommunikasjonsrådgivning',2407,'Helse/Miljø/Sikkerhet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Konsulenter/Frieyrker',1800,'lager_og_logistikk__logistikk_og_spedisjon.html?query=text%3Dlogistikk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kontormedarbeider/Sekretær',2690,'utdanning_og_forskning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kranfører',2300,'industri%2C_bygg_og_offshore__industri_og_produksjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kunderservice/Ordremottak',2300,'industri%2C_bygg_og_offshore__industri_og_produksjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kurs/Konferanse',2412,'Teknisk - maritim', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Kybernetikk',2309,'Transportmidler/Maskiner og utstyr', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Lager',2790,'utdanning_og_forskning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Landtransport',2408,'Prosjektledelse', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Ledelseogfellestjenester',2102,'Arbeidstagerorganisasjoner', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Lege',2104,'Internasjonale organisasjoner', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Legemiddelkonsulent',2101,'Næringslivs- og arbeidsgiverorg.', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Legesekretær',11,'Annet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Logistikk',100,'Administrasjon, økonomi og juss', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Lønn',400,'', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Lufttransport',11,'Annet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Maler',1903,'Bibliotek/Museer/Galleri', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Marineteknikk',1902,'Musikk/Dans', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Markedsføring',101,'Administrasjon, personal og kontor', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Maskinfører',201,'Bank/Finansielle tjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Maskiningeniør',490,'Helse, medisin og omsorg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Materialteknologi',2490,'Resturant og reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Media/Informasjon/PR',2190,'Industri, bygg, offshore', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Mekaniker',2190,'Industri, bygg, offshore', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Mekanikk',2190,'Industri, bygg, offshore', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Metallurgiskindustri/Metallvare',2100,'Interesseorganisasjoner', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Murer',2690,'Data og IKT', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Musikk/Dans/Drama',2700,'data_og_ikt / it_og_telecom', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Nærings-nytelsesmidler',1190,'Salg, Media og Markeføring', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Næringslivs-ogarbeidsgiverorg',2400,'On-/ offshore, olje og gass', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Offentligtjenesterogforvaltning',2490,'Resturant og reiseliv', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Økonomi/Finans',890,'Renhold, Service, Sikkerhet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Økonomi/Regnskap/Lønn',1190,'Salg, Media og Markeføring', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Olje-oggassutvinning',890,'Renhold, Service, Sikkerhet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Olje/gass/Off-Onshore/Maritim',1590,'Transport, lager og logistikk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Omsorgsmedarbeider',2790,'Utdanning og Forskning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Operatør/Vedlikehold',300,'Økonomi og regnskap', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Opplæring',1201,'Reklame', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Organiasjonsutvikling',1206,'Forlagvirksomhet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Personalarbeid/rekruttering',1205,'Internett', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Personligetjeneste-ogservice',1202,'Journalistikk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Politi/Brann/Toll',1401,'Kommunikasjonsrådgivning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Post-ogbudtjenester',1203,'Radio/TV/Film/Video', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Produksjon',1204,'Trykte Media', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Produktsalg',400,'administrasjon%2C_økonomi_og_juss__administrasjon%2C_personal_og_kontor__administrativ_ledelse', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Prosjekleder(ingeniør)',2404,'Drilling/Logging/Brønn/Boring', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Prosjektledelse',2400,'industri%2C_bygg_og_offshore__on-%2C_offshore%2C_olje_og_gass', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Prosjektledelse(olje/gass)',2402,'Geologi/Geofysikk/Reservoar', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Radio/TV/Film/Video',2407,'Helse/Miljø/Sikkerhet', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Regnskap',2410,'Ledelse og Fellestjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Reiseleder/Guide',2401,'Olje- og gassutvinning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Reiselivbransjen',2406,'Operatør/Vedlikehold', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Reiselivsmedarbeider',2408,'Prosjektledelse', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Rengjøringsmedarbeider',2412,'Teknisk - maritim', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Renhold/Renovasjon',901,'Rengjøringsmedarbeider', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Renovasjon',903,'Renovasjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Resepsjonist',904,'Skadesanering', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Revisjon/Skatterådgivning',902,'Vann- kloakk- og renseanlegg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Rørlegger',1307,'Markedsføring', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Saksbehandler',1305,'Produktsalg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Salg/Markedsføring',1307,'Markedsføring', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Sentralbord/Resepsjon',1304,'Telemarketing', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Service/sikkerhet',1303,'Tjenestesalg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Servicemedarbeider',1506,'Dagligvare', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Servitør',1503,'Detaljhandel/Butikksalg', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Sjåfør',1100,'renhold%2C_service_og_sikkerhet__vakt-_og_sikkerhetstjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Sjøtransport',1504,'Franchisetager', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Skadedyrkontroll/Skadesanering',601,'Hår- og skjønnhetspleie', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Skatt/Trygd',1100,'renhold%2C_service_og_sikkerhet__vakt-_og_sikkerhetstjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Snekker/tømrerm/fagbrev',1100,'renhold%2C_service_og_sikkerhet__vakt-_og_sikkerhetstjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Spedisjon/Befrakter/Fortoller',1100,'renhold%2C_service_og_sikkerhet__vakt-_og_sikkerhetstjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Stillasarbeider',905,'Vaktmestertjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Sveisere',1500,'Varehandel', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Sykepleier',1101,'Vekter', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Taktekker',515,'Veterinær', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Tannlege',1590,'Stilling/Transport, lager og logistikk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Tannlegeassistent',1700,'Lager', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Teknisk/Maritim',1600,'Landtransport', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Tekniskkonsulentvirksomhet',1800,'Logistikk/Spedisjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Teknisksalg',1590,'Stilling/Transport, lager og logistikk', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Telemarketing',1801,'Post- og budtjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Tjenestesalg',1601,'Sjåfører', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Transport/Logistikk/Lager',1602,'Sjøfart', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Transportmidler/Maskinerogutstyr',1800,'Logistikk/Spedisjon', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Transporttilknyttendetjenester',1611,'Transportknyttede tjenester', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Tre-ogverksindustri',805,'Barnehage', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Treningssenter',2805,'Professorat/Stipendiat', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Tryktemedia',2806,'Førskole', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Turoperatør/Chater',2801,'Grunnskole', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Ufaglærthåndverk',2800,'Stilling/Utdanning og forskning/Utdanning/', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Universitet/Høgskole',2803,'Universitet/Høgskole', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Utdanning/Undervisning/Forskning',2802,'Videregående skole', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Vaktmestertjenster',2804,'Voksenopplæring/Kurs', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Vann-,kloakkogrenseanlegg',301,'Regnskap/Controlling', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Varehandel',304,'Lønn', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Vektertjenester',300,'Økonomi og regnskap', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Veterinær',307,'Revisjon/Skatterådgivning', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Videregåendeskole',300,'Stilling/Administrasjon, økonomi og juss/Økonomi og regnskap', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Voksenopplæring',302,'Økonomi/Finans', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','ReisekonsulentBooking/Billettkontor',2502,'Booking', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Lagermedarbeider',1701,'Lagermedarbeider', 1311147487320); 
INSERT INTO valuemap (format, field, lookup, categoryid, zettvalue, updatedtime) VALUES ('rettbemanning','categories','Lagerm/truck',1702,'Truckfører / Vareplukker', 1311147487320); 