INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Til salgs', 'FOR_SALE', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Til leie', 'FOR_RENT', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Ønskes kjøpt', 'WANTED_BUY', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Ønskes leid', 'WANTED_RENT', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Byttes', 'TRADE', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Gis bort', 'GIVE_AWAY', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Gis bort/Byttes', 'GIVE_AWAY', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Arbeidskraft søkes', 'SERVICES_WANTED', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Tapt/Funnet', 'LOST_AND_FOUND', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Annet', 'OTHER', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Stilling ledig', 'JOB_AVAILABLE', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'country', 'NO', 'Norge', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'country', 'DK', 'Danmark', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'country', 'SE', 'Sverige', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'workarea', 'Kunst, kultur, sport og fritid', 'Kunst, Kultur, Sport og Fritid', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'workarea', 'Offentlige tjenester', 'Offentlige Tjenester', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'workarea', 'Ingeniør og teknikk', 'Ingeniør og Teknikk', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'workarea', 'Helse, Sosial og Omsorg', 'Helse, Sykepleie, Sosial og Omsorg', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'workarea', 'Undervisning og pedagogikk', 'Undervisning og Pedagogikk', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'workarea', '- Velg arbeidsområde -', 'Annet', 1311062802);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('robot', 'transaction', 'Arbeid utføres', 'JOB_PERFORMED', 1311062802);

INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrrobot', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrcruit', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrutleiem', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrrekr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zreasy', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrfred', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrh4h', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'robot', 'zrtopt', 2, 'password');