INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Ingen kontaktinfo skal vises', 'SHOW_NONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Email vises', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Telefonnummer vises', 'SHOW_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Navn og telefonnummer', 'SHOW_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Navn og Telefonnummer', 'SHOW_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Navn og telefonnummer vises', 'SHOW_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Epost og telefonnummer vises', 'SHOW_EMAIL_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Email, navn og telefonnummer vises', 'SHOW_EMAIL_NAME_PHONE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'All kontaktinfo kan vises på annonsen.', 'SHOW_ALL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'defaultprivacy', '10031', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'defaultprivacy', '10009', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'defaultprivacy', '10025', 'SHOW_EMAIL', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Selges', 'FOR_SALE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Til leie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Til Leie', 'FOR_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Ønskes kjøpt', 'WANTED_BUY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Ønskes leid', 'WANTED_RENT', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Byttes', 'TRADE', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Gis bort', 'GIVE_AWAY', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Arbeidskraft søkes', 'SERVICES_WANTED', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Tapt/Funnet', 'LOST_AND_FOUND', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Annet', 'OTHER', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'country', 'Norway', 'Norge', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'country', 'Sweden', 'Sverige', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'country', 'Denmark', 'Danmark', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'country', 'Spain', 'Spania', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'country', 'Thailand', 'Thailand', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'source', 'Forhandler', 'Forhandler', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'source', 'Privat selger', 'Privat', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Helse, Sosial og Omsorg', 'Helse, Sykepleie, Sosial og Omsorg', 490, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Organisasjon, menighet og humanitær', 'Organisasjon, Menighet og Humanitær',1890, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Juridiske tjenester', 'Juridiske Tjenester',400, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Bud- og transport-tjenester', 'Bud- og Transport-tjenester',1590, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'IT-tjenester', 'Data og IT',2690, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Salgstjenester', 'Salg',1300, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Helse og skjønnhet', 'Helse og Skjønnhet',600, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Undervisningstjenester', 'Undervisning og Pedagogikk',2790, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Undervisning og pedagogikk', 'Undervisning og Pedagogikk',2790, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Håndverkstjenester', 'Håndverksfag',2200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Håndtverkstjenester', 'Håndverksfag',2200, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Dagmamma/Barnepass', 'Dagmamma/Praktikant',803, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Snøscootere', 'Snøscooter',10500, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Garasje/Opplag', 'Garasje/opplag',1600, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Skjærgårdsjeep/Landstedsbåt', 'Skjærgårdsjeep/Landstedbåt',13500, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Mat og Drikke', 'Mat og drikke',7163, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Sport og Fritid', 'Sport- og fritidsutstyr',7655, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Trebåt/snekke', 'Trebåt/Snekke',13550, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Brunevarer og elektriske artik', 'Brunevarer og elektriske artikler',5833, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Landbruks- maskiner/utstyr', 'Landbruk - maskiner/utstyr',10793, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, categoryid, updatedtime) VALUES ('tietoenator', 'category', 'Vedlikehold/Oppussing/Rydding','Vedlikehold/Oppussing/Rydding',900, 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'transaction', 'Arbeid utføres', 'JOB_PERFORMED', 1311147487320);
INSERT INTO valuemap ( format, field, lookup, zettvalue, updatedtime) VALUES ('tietoenator', 'privacy', 'Anonym', 'SHOW_EMAIL', 1311147487320);


INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaribl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaarbe', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaberg', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zasoav', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zafinn', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zbfird', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zafima', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zafrem', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zagudb', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaglam', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zahear', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zahafo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zahade', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zahama', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zakvin', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zalofo', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zarb', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zanamd', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zanord', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zanoly', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaospr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaopar', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zafrbl', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaostp', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zarana', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zastjb', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zasp', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zateav', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zatikr', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zaaura', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'ftp1050782', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'ftp10082', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'ftp485292', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zxroga', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'ftp609363', 2, 'password');
INSERT INTO partnerlogin ( customerformat, login, protocol, loginpassword) VALUES ( 'tietoenator', 'zahala', 2, 'password');

INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'RIB/RIB', 10019, 'Ringerikes Blad', 'password' FROM partnerlogin WHERE login='zaribl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WEB/RIB', 10019, 'Ringerikes Blad', 'password' FROM partnerlogin WHERE login='zaribl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAR/AR', 10041, 'Arbeidets Rett', 'password' FROM partnerlogin WHERE login='zaarbe';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WBA/BA', 10031, 'Bergensavisen', 'password' FROM partnerlogin WHERE login='zaberg';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WBA/BAM', 10031, 'Bergensavisen', 'password' FROM partnerlogin WHERE login='zaberg';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WEB/SOA', 10039, 'Sogn Avis', 'password' FROM partnerlogin WHERE login='zasoav';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WFD/FD', 10047, 'Finnmark Dagblad', 'password' FROM partnerlogin WHERE login='zafinn';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WFI/FIR', 10037, 'Firda', 'password' FROM partnerlogin WHERE login='zbfird';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WFM/DF', 10051, 'Finnmarken', 'password' FROM partnerlogin WHERE login='zafima';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WFI/FPO', 10038, 'Firdaposten', 'password' FROM partnerlogin WHERE login='zbfird';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WFR/FRE', 10050, 'Fremover', 'password' FROM partnerlogin WHERE login='zafrem';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WGD/GD', 10026, 'Gudbrandsdolen Dagningen', 'password' FROM partnerlogin WHERE login='zagudb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WGL/GL6', 10027, 'Glåmdalen', 'password' FROM partnerlogin WHERE login='zaglam';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHA/HLA', 10049, 'Helgeland Arbeiderblad', 'password' FROM partnerlogin WHERE login='zahear';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHF/HF', 10070, 'Hardanger Folkeblad', 'password' FROM partnerlogin WHERE login='zahafo';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHL/HAD', 10030, 'Hadeland', 'password' FROM partnerlogin WHERE login='zahade';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHM/HA', 10024, 'Hamar Arbeiderblad', 'password' FROM partnerlogin WHERE login='zahama';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WKV/KV', 10069, 'Kvinnheringen', 'password' FROM partnerlogin WHERE login='zakvin';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WLO/LP', 10052, 'Lofotposten', 'password' FROM partnerlogin WHERE login='zalofo';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMO/IAB', 10022, 'Indre Akershus Blad', 'password' FROM partnerlogin WHERE login='zarb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMO/RB', 10001, 'Romerikes Blad', 'password' FROM partnerlogin WHERE login='zarb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNA/NAM', 10036, 'Namdalsavisa', 'password' FROM partnerlogin WHERE login='zanamd';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNF/ANB', 10035, 'Avisa Nordland Bilag', 'password' FROM partnerlogin WHERE login='zanord';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNF/AN', 10035, 'Avisa Nordland', 'password' FROM partnerlogin WHERE login='zanord';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNL/NLY', 10040, 'Nordlys', 'password' FROM partnerlogin WHERE login='zanoly';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/DEM', 10010, 'Demokraten', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/IØ', 10012, 'Smaalenene Avis', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/MD', 10011, 'Moss Dagblad', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/RA', 10015, 'Rakkestad Avis', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/SA', 10008, 'Sarpsborg Arbeiderblad', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/AA', 10014, 'Akershus Amtstidende', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOL/OA', 10025, 'Oppland Arbeiderblad', 'password' FROM partnerlogin WHERE login='zaopar';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOM/FB', 10006, 'Fredrikstad Blad', 'password' FROM partnerlogin WHERE login='zafrbl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOM/MO', 10007, 'Moss Avis', 'password' FROM partnerlogin WHERE login='zafrbl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOM/ØB', 10009, 'Østlandets Blad', 'password' FROM partnerlogin WHERE login='zafrbl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/JB', 10065, 'Jarlsberg Avis', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/OP', 10064, 'Østlands-Posten', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/PD', 10060, 'Porsgrunn Dagblad', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WRB/RB', 10048, 'Rana Blad', 'password' FROM partnerlogin WHERE login='zarana';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WSB/MB', 10053, 'Malvik-bladet', 'password' FROM partnerlogin WHERE login='zastjb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WSB/SB', 10042, 'Stjørdalens Blad', 'password' FROM partnerlogin WHERE login='zastjb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WSP/SMP', 10002, 'Sunnmørsposten', 'password' FROM partnerlogin WHERE login='zasp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WSP/VV', 10074, 'Vikebladet Vestposten', 'password' FROM partnerlogin WHERE login='zasp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTA/TA', 10057, 'Telemarksavisa', 'password' FROM partnerlogin WHERE login='zateav';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/TK', 10004, 'Tidens Krav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAA/OPD', 10046, 'Opdalingen', 'password' FROM partnerlogin WHERE login='zaaura';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAA/AA', 10034, 'Aura Avis', 'password' FROM partnerlogin WHERE login='zaaura';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'RIB/BP', 10021, 'Bygdeposten', 'password' FROM partnerlogin WHERE login='zaribl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'Hallingdølen', 10018, 'Hallingdølen', 'password' FROM partnerlogin WHERE login='zbhall';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/AA', 10067, 'Aust Agder Blad', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/MSD', 10008, 'Samkjøring mellom Demokraten og Sarpsborg Arbeiderblad', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WBV/BV', 10081, 'Bladet Vesterålen', 'password' FROM partnerlogin WHERE login='ftp1050782';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WDA/DA', 10082, 'Dagsavisen', 'password' FROM partnerlogin WHERE login='ftp10082';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'BV/BV', 10081, 'Samkjøring', 'password' FROM partnerlogin WHERE login='ftp1050782';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/IEA', 10008, 'Samkjøring', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/SM', 10012, 'Smaalenene Avis', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/AAT', 10067, 'Aust Agder Blad Tabloid', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/LOY', 10066, 'Øyene', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/TP', 10068, 'Tvedestrandsposten', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOP/EB', 1473024, 'Eikerbladet', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/AA', 10034, 'Aura Avis i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/NA', 10036, 'Namdalsavisa i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/SB', 10042, 'Stjørdalens blad i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/AR', 10041, 'Arbeidets Rett i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/MA', 10053, 'Malvikbladet i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNF/SAL', 1473089, 'Indre Salten i samkjøring med Avisa Nordland', 'password' FROM partnerlogin WHERE login='zanord';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAR/TNA', 10036, 'Namdalsavisa i samkjøring med Arbeidets Rett', 'password' FROM partnerlogin WHERE login='zaarbe';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAR/TMA', 10053, 'Malvikbladet i samkjøring med Arbeidets Rett', 'password' FROM partnerlogin WHERE login='zaarbe';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAR/TOP', 10046, 'Opdalingen i samkjøring med Arbeidets Rett', 'password' FROM partnerlogin WHERE login='zaarbe';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAR/TST', 10042, 'Stjørdalen i samkjøring med Arbeidets Rett', 'password' FROM partnerlogin WHERE login='zaarbe';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WAR/TBY', 1473103, 'Byavisa i samkjøring med Arbeidets Rett', 'password' FROM partnerlogin WHERE login='zaarbe';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WFI/AAL', 10037, 'Firda produksjon i samkjøring med Firda', 'password' FROM partnerlogin WHERE login='zbfird';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WEB/BP', 10021, 'Bygdeposten i samkjøring med Ringerikes blad', 'password' FROM partnerlogin WHERE login='zaribl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOL/HAD', 10030, 'Hadeland i samkjøring med Oppland Arbeiderblad', 'password' FROM partnerlogin WHERE login='zaopar';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTA/PD', 10060, 'Porsgrunns Dagblad i samkjøring med Telemarksavisa', 'password' FROM partnerlogin WHERE login='zateav';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTA/RA', 1473156, 'Rjukan Arbeiderblad i samkjøring med Telemarksavisa', 'password' FROM partnerlogin WHERE login='zateav';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMO/RØV', 10001, 'Øvre Romerikes blad i samkjøring med Romerikes blad', 'password' FROM partnerlogin WHERE login='zarb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMO/RSR', 10001, 'Skedsmo/Rælingen i samkjøring med Romerikes blad', 'password' FROM partnerlogin WHERE login='zarb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMO/RR', 10001, 'Romeriksen i samkjøring med Romerikes blad', 'password' FROM partnerlogin WHERE login='zarb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMO/RLØ', 10001, 'Romerikes blad Lørenskog', 'password' FROM partnerlogin WHERE login='zarb';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHM/LA', 592247, 'Lokalavisa Sør-Østerdal', 'password' FROM partnerlogin WHERE login='zahama';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/RB', 10048, 'Rana blad i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/HD', 1438960, 'Halden Dagblad samkjørt', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/IAB', 10022, 'Indre Akershus Blad', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHA/RBA', 10048, 'Rana blad ny kode', 'password' FROM partnerlogin WHERE login='zarana';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/RBA', 10048, 'Rana blad ny kode', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WRB/RBA', 10048, 'Rana blad ny kode', 'password' FROM partnerlogin WHERE login='zarana';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/OPD', 10046, 'Opdalingen i samkjøring med Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/NAM', 10036, 'Namdalsavisa i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/STJ', 10042, 'Stjørdalens blad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/OPD', 10046, 'Opdalingen i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/LSØ', 592247, 'Lokalavisa Sør-Østerdal i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/BPO', 10021, 'Bygdeposten i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/HA', 10024, 'Hamar Arbeiderblad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/HD', 1438960, 'Halden Dagblad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/SA', 10008, 'Sarpsborg Arbeiderblad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/DEM', 10010, 'Demokraten i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/MD', 10011, 'Moss Dagblad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/IØS', 10012, 'Smaalenenes Avis i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/RB', 10001, 'Romerikes blad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/IAB', 10022, 'Indre Akershus blad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/HL', 10030, 'Hadeland blad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/GL6', 10027, 'Glåmdalen i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/GD', 10026, 'Gudbrandsdolen Dagningen i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/OA', 10025, 'Oppland Arbeiderblad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/AR', 10041, 'Arbeidets Rett i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/RIB', 10019, 'Ringerikes Blad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/AA', 10014, 'Akerhus Armtstidende i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/ENE', 1430589, 'Enebakk Avis i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/VAR', 770563, 'Varingen i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WRI/RIB', 10019, 'Ringerikes blad', 'password' FROM partnerlogin WHERE login='zaribl';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/NL', 10040, 'Nordlys i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/AN', 10035, 'Avisa Nordland i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/BV', 10081, 'Bladet Vesterålen i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/FR', 10050, 'Fremover i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/LO', 10052, 'Lofotposten i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/FI', 10051, 'Finnmarken i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/FD', 10047, 'Finnmark Dagblad i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/RB', 10048, 'Rana Blad i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/HA', 10049, 'Helgeland Arbeiderblad i Medianor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WTK/HA', 10049, 'Hamar Arbeiderblad i Tidenskrav', 'password' FROM partnerlogin WHERE login='zatikr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WOF/EA', 1430589, 'Enebakk avis', 'password' FROM partnerlogin WHERE login='zaospr';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/RBA', 10048, 'Ranablad samkjøring med Media Nor', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/DF', 10051, 'Finnmarken ny Medianor kode', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/FRE', 10050, 'Fremover ny Medianor kode', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/HLA', 10049, 'Helgeland ny Medianor kode', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/LP', 10052, 'Lofotposten ny Medianor kode', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WMN/NLY', 10040, 'Nordlys ny Medianor kode', 'password' FROM partnerlogin WHERE login='ftp485292';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WRA/RGA', 10055, 'Rogaland Avis via mpress', 'password' FROM partnerlogin WHERE login='zxroga';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VJA/JB', 10065, 'Jarlsberg Avis samkjørt med Østlands-Posten', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VJOY/OP', 10064, 'Østlands-posten new productcode', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VJOY/LOY', 10066, 'Øyene samkjørt med østlandsposten', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VJOY/TP', 10068, 'Tvedestrandsposten samkjørt', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VJOY/PD', 10060, 'Porsgrunn Dagblad samkjørt', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VJOY/JB', 10065, 'Jarlsberg Avis samkjørt', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VLO/LOY', 10066, 'Øyene samkjørt', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VOJ/OP', 10064, 'Østlandsposten og Jarlsberg', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VOJ/JB', 10065, 'Jarlsberg Avis samkjørt med østlandsposten', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'VOP/OP', 10064, 'Østlandsposten', 'password' FROM partnerlogin WHERE login='zaostp';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WNR/HAB', 10013, 'Halden Arbeiderblad i NR1', 'password' FROM partnerlogin WHERE login='ftp609363';
INSERT INTO partnermap ( partnerlogin_id, identifier, zclientid, description, partnermappassword) SELECT id,'WHL/HA', 10013, 'Halden Arbeiderblad', 'password' FROM partnerlogin WHERE login='zahala';